package app.qingledger;
import org.json.*;import java.util.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public class ServerTest {
 static class Memory implements LocalServer.Store{Map<String,String> m=new LinkedHashMap<>(),before;long rev=0,old;boolean ok;public long revision(){return rev;}public JSONArray all(){JSONArray a=new JSONArray();for(String s:m.values())a.put(new JSONObject(s));return a;}public JSONObject get(String id){return m.containsKey(id)?new JSONObject(m.get(id)):null;}public void put(JSONObject r){m.put(r.getString("id"),r.toString());}public void delete(String id){m.remove(id);}public void begin(){before=new LinkedHashMap<>(m);old=rev;ok=false;}public void success(){ok=true;}public void end(){if(!ok){m=before;rev=old;}}public void setRevision(long r){rev=r;}}
 static class Result{int status;JSONObject data;Result(int s,JSONObject d){status=s;data=d;}}
 static int port;
 static Result call(String path,JSONObject data,String token)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("http://127.0.0.1:"+port+path).openConnection();c.setRequestProperty("Authorization","Bearer "+token);if(data!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");byte[] bytes=data.toString().getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(bytes.length);try(OutputStream out=c.getOutputStream()){out.write(bytes);}}int status=c.getResponseCode();InputStream stream=status<400?c.getInputStream():c.getErrorStream();JSONObject body=stream==null?new JSONObject():new JSONObject(new String(LocalServer.readAll(stream),StandardCharsets.UTF_8));c.disconnect();return new Result(status,body);}
 static JSONObject obj(String s){return new JSONObject(s);}
 static Result mutate(JSONObject r,Long expected,String token)throws Exception{return call("/api/mutate",new JSONObject().put("ops",new JSONArray().put(new JSONObject().put("action","put").put("record",r).put("expected",expected==null?JSONObject.NULL:expected))),token);}
 static void check(boolean b,String label){if(!b)throw new AssertionError(label);}
 public static void main(String[] args)throws Exception{Memory db=new Memory();LocalServer server=new LocalServer("test".getBytes(),db,0);server.start();port=server.port();try{
 check(call("/api/state",null,"").status==401,"unauthorized");check(call("/api/login",obj("{code:'bad',name:'甲'}"),"").status==403,"wrong code");String a=call("/api/login",new JSONObject().put("code",server.code).put("name","甲"),"").data.getString("token"),b=call("/api/login",new JSONObject().put("code",server.code).put("name","乙"),"").data.getString("token");
 JSONObject r=obj("{id:'test',type:'expense',cents:2860,purpose:'午饭',category:'餐饮',date:'2026-09-27',account:'微信',project:'旅行',note:'',created:1234,photos:[]}");r.getJSONArray("photos").put("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=");check(mutate(r,null,a).status==200,"create");JSONObject first=call("/api/state",null,b).data.getJSONArray("records").getJSONObject(0);check(first.getString("author").equals("甲")&&first.getJSONArray("photos").length()==1,"shared photos");long rev=first.getLong("revision");check(call("/api/state?since="+rev,null,b).data.getBoolean("unchanged"),"incremental");ExecutorService ex=Executors.newFixedThreadPool(2);List<Future<Result>> results=ex.invokeAll(Arrays.asList(()->mutate(new JSONObject(r.toString()).put("cents",3000),rev,a),()->mutate(new JSONObject(r.toString()).put("cents",3200),rev,b)));List<Integer> statuses=Arrays.asList(results.get(0).get().status,results.get(1).get().status);ex.shutdown();check(statuses.contains(200)&&statuses.contains(409),"concurrency");
 check(mutate(new JSONObject(r.toString()).put("id","bad").put("date","2026-02-31"),null,a).status==400,"date validation");check(mutate(new JSONObject(r.toString()).put("id","bad").put("photos",new JSONArray().put("data:image/jpeg;base64,YWJj")),null,a).status==400,"image validation");
 JSONArray ops=new JSONArray().put(new JSONObject().put("action","import").put("record",new JSONObject(r.toString()).put("id","second"))).put(new JSONObject().put("action","import").put("record",new JSONObject(r.toString()).put("id","bad").put("cents",-1)));check(call("/api/mutate",new JSONObject().put("ops",ops),a).status==400&&db.m.size()==1,"atomic rollback");
 long current=db.get("test").getLong("revision");check(call("/api/mutate",obj("{ops:[{action:'delete',id:'test',expected:"+rev+"}]}"),b).status==409,"stale delete");check(call("/api/mutate",obj("{ops:[{action:'delete',id:'test',expected:"+current+"}]}"),b).status==200,"delete");check(mutate(r,current,a).status==409,"deleted record conflict");
 System.out.println("PASS: native HTTP core: login, authorization, shared images, sync, simultaneous edits, invalid date/image, atomic batch rollback, stale deletion, deletion and resurrection prevention.");
 }finally{server.close();}}
}
